# Generated by Django 5.2.4 on 2025-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อคอร์ส')),
                ('level', models.CharField(max_length=100, verbose_name='ระดับ')),
                ('category', models.CharField(max_length=100, verbose_name='สายงาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'คอร์ส',
                'verbose_name_plural': 'คอร์ส',
                'ordering': ['-created_at'],
            },
        ),
    ]
