# Generated by Django 5.2.4 on 2025-10-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อบทเรียน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดบทเรียน')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='คอร์ส')),
            ],
            options={
                'verbose_name': 'บทเรียน',
                'verbose_name_plural': 'บทเรียน',
                'ordering': ['course', 'order'],
            },
        ),
    ]
