# Generated by Django 5.2.4 on 2025-10-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อเนื้อหา/ลิงก์')),
                ('kind', models.CharField(choices=[('youtube', 'YouTube'), ('external', 'External URL'), ('file', 'File')], default='external', max_length=16)),
                ('url', models.URLField(blank=True, verbose_name='ลิงก์')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_assets/', verbose_name='ไฟล์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='courses.lesson', verbose_name='บทเรียน')),
            ],
        ),
    ]
