# Generated by Django 5.2.4 on 2025-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'order', 'id'], 'verbose_name': 'บทเรียน', 'verbose_name_plural': 'บทเรียน'},
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_lesson_order_per_course'),
        ),
    ]
