# Generated by Django 5.2.4 on 2025-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดงาน')),
                ('position_type', models.CharField(max_length=200, verbose_name='ตำแหน่งงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='jobs', to='courses.course', verbose_name='คอร์สที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'งาน',
                'verbose_name_plural': 'งาน',
                'ordering': ['-created_at'],
            },
        ),
    ]
