# Generated by Django 5.2.4 on 2025-10-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlink',
            name='role',
            field=models.CharField(choices=[('main', 'Main Video'), ('sign', 'Sign Language Video')], default='main', max_length=8, verbose_name='บทบาท'),
        ),
    ]
