# Generated by Django 5.2.4 on 2025-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonlink_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlink',
            name='file',
        ),
        migrations.AlterField(
            model_name='lessonlink',
            name='role',
            field=models.CharField(choices=[('main', 'Main Video'), ('sign', 'Sign Language Video')], default='main', max_length=16),
        ),
    ]
