# Generated by Django 5.2.7 on 2025-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lessonlink_file_alter_lessonlink_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='ลิงก์วิดีโอ'),
        ),
    ]
