# Generated by Django 5.2.4 on 2025-10-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='คำถาม')),
                ('words', models.JSONField(default=list, verbose_name='คำที่ให้เลือก')),
                ('correct_order', models.JSONField(default=list, verbose_name='ลำดับที่ถูกต้อง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='คอร์สที่เกี่ยวข้อง')),
            ],
        ),
    ]
