# Generated by Django 5.2.4 on 2025-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
    ]
