# Generated by Django 5.2.4 on 2025-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='สถานที่ทำงาน'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, verbose_name='เงินเดือน'),
        ),
    ]
