# Generated by Django 5.2.4 on 2025-10-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_job_company_job_location_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_covers/', verbose_name='รูปบทเรียน'),
        ),
    ]
