# Generated by Django 5.2.4 on 2025-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_lesson_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlink',
            name='duration_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonlink',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
